import os
import sys
import traceback
from datetime import datetime

from config import OUTPUT_DIR
from news_fetcher import get_trending_ai_topic
from script_writer import load_script, validate_script
from tts_engine import generate_continuous_audio, calculate_scene_durations
from scene_builder import build_scenes
from video_assembler import assemble_video_continuous
from database import init_db, insert_video, update_video_status
from feedback_loop import build_pipeline_context, update_claude_md_insights
from performance_analyzer import generate_insights
from youtube_analytics import sync_all_analytics
from email_notifier import send_review_email, send_error_alert


def run_pipeline():
    print("=" * 60)
    print("AI/TECH NEWS VIDEO GENERATOR")
    print("=" * 60)

    try:
        # Step 0: Initialize database
        init_db()

        # Step 1: Analyze past performance (non-fatal)
        print("\n[1/8] Syncing analytics and generating insights...")
        try:
            sync_all_analytics()
            generate_insights()
            update_claude_md_insights()
            print("  Analytics synced and insights updated.")
        except Exception as e:
            print(f"  WARNING: Analytics sync failed (non-fatal): {e}")

        # Step 2: Build pipeline context from performance data
        print("\n[2/8] Building pipeline context...")
        try:
            context = build_pipeline_context()
            print(f"  Best hook: {context.get('best_hook_style')}")
            print(f"  Best pattern: {context.get('best_script_pattern')}")
            print(f"  A/B test: {context.get('ab_test', {}).get('variable', 'none')}")
        except Exception as e:
            print(f"  WARNING: Context build failed (non-fatal): {e}")
            context = {}

        # Step 3: Load script (generated by agent team)
        script_path = os.path.join(OUTPUT_DIR, "script.json")
        if not os.path.exists(script_path):
            print(f"ERROR: No script found at {script_path}")
            print("Run the agent team to generate a script first.")
            sys.exit(1)

        print("\n[3/8] Loading video script...")
        title, scenes, full_narration = load_script(script_path)

        if not scenes:
            print("ERROR: No scenes in script.")
            sys.exit(1)

        print(f"  Title: {title}")
        print(f"  Scenes: {len(scenes)}")
        print(f"  Narration: {len(full_narration)} chars")

        is_valid, issues = validate_script(scenes)
        if not is_valid:
            print("  WARNING: Script validation issues:")
            for issue in issues:
                print(f"    - {issue}")

        # Step 4: Generate continuous TTS audio (one file)
        print("\n[4/8] Generating continuous narration audio...")
        audio_path = os.path.join(OUTPUT_DIR, "audio", "full_narration.wav")
        total_duration = generate_continuous_audio(full_narration, audio_path)

        if not total_duration:
            print("ERROR: No audio generated.")
            sys.exit(1)

        print(f"  Total audio duration: {total_duration:.1f}s")

        # Step 5: Build visual frames
        print("\n[5/8] Building visual frames...")
        frame_paths = build_scenes(scenes)

        if not frame_paths:
            print("ERROR: No frames generated.")
            sys.exit(1)

        print(f"  Generated {len(frame_paths)} frames")

        # Step 6: Calculate scene durations from narration proportions
        print("\n[6/8] Calculating scene timing...")
        scene_durations = calculate_scene_durations(scenes, total_duration)
        for i, dur in enumerate(scene_durations):
            print(f"  Scene {i+1}: {dur:.1f}s")

        # Step 7: Assemble video with continuous audio
        print("\n[7/8] Assembling final video...")
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        output_path = os.path.join(OUTPUT_DIR, f"video_{timestamp}.mp4")

        assemble_video_continuous(
            frame_paths=frame_paths,
            scene_durations=scene_durations,
            audio_path=audio_path,
            output_path=output_path,
        )

        # Step 8: Store in DB and send for review
        print("\n[8/8] Storing in database and sending review email...")
        topic_data = {}
        topic_path = os.path.join(OUTPUT_DIR, "topic.json")
        if os.path.exists(topic_path):
            import json
            with open(topic_path, "r", encoding="utf-8") as f:
                topic_data = json.load(f)

        topic = topic_data.get("topic", "unknown")
        video_id = insert_video(
            title=title,
            topic=topic,
            topic_category=topic_data.get("topic_category", ""),
            script_pattern=context.get("best_script_pattern", ""),
            hook_style=context.get("best_hook_style", ""),
            video_file_path=os.path.abspath(output_path),
        )
        update_video_status(video_id, "pending_review")

        # Find thumbnail (first frame)
        thumbnail_path = frame_paths[0] if frame_paths else None
        send_review_email(
            video_id=video_id,
            title=title,
            topic=topic,
            script_summary=full_narration[:500],
            thumbnail_path=thumbnail_path,
        )

        print("\n" + "=" * 60)
        print(f"Done! Video saved to: {os.path.abspath(output_path)}")
        print(f"Total duration: {total_duration:.1f}s")
        print(f"Video ID: {video_id} (status: pending_review)")
        print("=" * 60)

        return video_id

    except SystemExit:
        raise
    except Exception as e:
        print(f"\nFATAL ERROR: {e}")
        traceback.print_exc()
        try:
            send_error_alert(type(e).__name__, str(e), traceback.format_exc())
        except Exception:
            print("  WARNING: Failed to send error alert email.")
        raise


if __name__ == "__main__":
    run_pipeline()
