"""
Script validator and loader — reads script JSON generated by Claude Code subagent,
validates against CLAUDE.md rules, and returns scene list for the pipeline.
"""

import json
import os
import re

# --- Banned phrases from CLAUDE.md ---

BANNED_TIER1 = [
    "delve", "delving", "dive into", "deep dive", "unpack", "let's unpack",
    "in today's rapidly evolving landscape", "in the ever-evolving landscape",
    "in today's fast-paced world", "game-changer", "game-changing",
    "revolutionize", "revolutionary", "realm", "tapestry", "testament",
    "nuance", "nuanced", "paradigm", "paradigm shift",
    "leverage", "utilize", "facilitate", "foster", "synergy", "holistic",
    "robust", "seamless", "seamlessly", "cutting-edge", "groundbreaking",
    "transformative", "pivotal", "multifaceted", "comprehensive",
    "it's important to note that", "it's worth mentioning that",
    "at the end of the day", "moving forward", "in terms of",
    "when it comes to", "embark on a journey", "shed light on", "pave the way",
]

BANNED_TIER2_PATTERNS = [
    r"whether you'?re a .+ or a .+",
    r"not only.+but also",
    r"on the one hand.+on the other hand",
    r"from .+ to .+, .+ is",
    r"in conclusion", r"to sum up", r"in summary",
    r"without further ado",
    r"^(importantly|notably|interestingly),",
    r"let's explore", r"let's take a look at",
    r"first and foremost",
    r"last but not least",
]

BANNED_NAVIGATE_PATTERN = r"navigate\s+(the\s+)?(challenges|landscape|world|complexities|waters|terrain)"

VALID_VISUAL_TYPES = [
    "text_bold", "text_only", "fullscreen_image", "meme_fullscreen",
    "image_with_text", "image_collage", "image_grid", "article_screenshot",
]


def load_script(path="output/script.json"):
    """Load script JSON from file. Returns (title, scenes, full_narration) tuple."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    title = data.get("title", "Untitled")
    scenes = data.get("scenes", [])

    # Normalize: treat text_only as text_bold (merged)
    for scene in scenes:
        if scene.get("visual_type") == "text_only":
            scene["visual_type"] = "text_bold"

    # Get full_narration or auto-generate from scene narrations
    full_narration = data.get("full_narration", "")
    if not full_narration:
        full_narration = " ".join(s.get("narration", "") for s in scenes if s.get("narration"))

    return title, scenes, full_narration


def validate_script(scenes):
    """Validate a script against CLAUDE.md rules.

    Returns:
        tuple: (is_valid: bool, errors: list[str])
    """
    errors = []

    if not scenes:
        return False, ["Script has no scenes"]

    # Check scene count (5-min video needs 30-60 scenes)
    if len(scenes) < 15:
        errors.append(f"Too few scenes: {len(scenes)} (minimum 15 for 5-min video)")
    if len(scenes) > 80:
        errors.append(f"Too many scenes: {len(scenes)} (maximum 80)")

    # Check hook is first (no bad openers)
    first_narration = scenes[0].get("narration", "").lower()
    bad_hooks = [
        "hey everyone", "welcome back", "in today's video",
        "before we get started", "let's dive in", "let's dive",
    ]
    for bh in bad_hooks:
        if bh in first_narration:
            errors.append(f"Bad hook phrase found: '{bh}'")

    # Check banned phrases in all narration
    all_narration = " ".join(s.get("narration", "") for s in scenes).lower()

    for phrase in BANNED_TIER1:
        if phrase.lower() in all_narration:
            errors.append(f"Banned phrase found: '{phrase}'")

    for pattern in BANNED_TIER2_PATTERNS:
        if re.search(pattern, all_narration, re.IGNORECASE | re.MULTILINE):
            errors.append(f"Banned pattern found: '{pattern}'")

    if re.search(BANNED_NAVIGATE_PATTERN, all_narration, re.IGNORECASE):
        errors.append("Banned metaphorical 'navigate' usage found")

    # Check bad outros
    last_narration = scenes[-1].get("narration", "").lower()
    bad_outros = [
        "like and subscribe", "hit the bell", "let me know in the comments",
        "thanks for watching",
    ]
    for bo in bad_outros:
        if bo in last_narration:
            errors.append(f"Bad outro phrase found: '{bo}'")

    # Check content requirements
    has_opinion = any(
        m in all_narration for m in [
            "my take", "i think", "honestly", "i believe",
            "opinion", "i'd bet", "i'm betting",
        ]
    )
    if not has_opinion:
        errors.append("Missing required: at least 1 opinion/hot take")

    has_uncertainty = any(m in all_narration for m in [
        "we don't know", "could be wrong", "could i be wrong",
        "unclear", "uncertain", "might not", "hard to say",
        "could go either way", "don't have all the answers",
        "we'll see", "time will tell", "too early to tell",
    ])
    if not has_uncertainty:
        errors.append("Missing uncertainty acknowledgment in narration")

    has_specific = re.search(
        r"\b(january|february|march|april|may|june|july|august|september"
        r"|october|november|december|\d{4}|\d+%|\$\d+|\d+ (million|billion"
        r"|thousand|months|weeks|days|hours))\b",
        all_narration,
        re.IGNORECASE,
    )
    if not has_specific:
        errors.append("Missing required: at least 1 specific number, date, or data point")

    # Check sentence length (under 25 words)
    for scene in scenes:
        narration = scene.get("narration", "")
        sentences = re.split(r'[.!?]+', narration)
        for sent in sentences:
            words = sent.strip().split()
            if len(words) > 25:
                errors.append(
                    f"Scene {scene.get('scene_id', '?')}: sentence over 25 words "
                    f"({len(words)} words): '{sent.strip()[:60]}...'"
                )

    # Check contractions
    no_contraction = [
        (r"\bit is\b", "it's"), (r"\bthey are\b", "they're"),
        (r"\bwill not\b", "won't"), (r"\bcan not\b", "can't"),
        (r"\bcannot\b", "can't"), (r"\bdoes not\b", "doesn't"),
        (r"\bdo not\b", "don't"), (r"\bwe are\b", "we're"),
        (r"\byou are\b", "you're"),
    ]
    for pattern, contraction in no_contraction:
        if re.search(pattern, all_narration, re.IGNORECASE):
            errors.append(f"Use contraction '{contraction}' instead of full form")

    # Check visual types are valid
    for scene in scenes:
        vtype = scene.get("visual_type", "")
        if vtype and vtype not in VALID_VISUAL_TYPES:
            errors.append(f"Scene {scene.get('scene_id', '?')}: invalid visual_type '{vtype}'")

    # Check no consecutive same visual_type
    for i in range(1, len(scenes)):
        if scenes[i].get("visual_type") == scenes[i-1].get("visual_type"):
            vtype = scenes[i].get("visual_type")
            errors.append(
                f"Scenes {scenes[i-1].get('scene_id', '?')}-{scenes[i].get('scene_id', '?')}: "
                f"consecutive same visual_type '{vtype}'"
            )

    # Check synonym-chain filler (e.g., "Not X. Not Y. Z." pattern)
    filler_pattern = r"not \w+[\.\,]\s*not \w+[\.\,]\s*\w+"
    if re.search(filler_pattern, all_narration, re.IGNORECASE):
        errors.append("Synonym-chain filler detected (e.g., 'Not X. Not Y. Z.') — just state it directly")

    is_valid = len(errors) == 0
    return is_valid, errors


if __name__ == "__main__":
    if os.path.exists("output/script.json"):
        print("Loading script from output/script.json...")
        title, scenes = load_script()
        print(f"Title: {title}")
        print(f"Scenes: {len(scenes)}")

        for scene in scenes:
            print(f"\n--- Scene {scene.get('scene_id', '?')} ---")
            print(f"  Visual:  {scene.get('visual_type')}")
            print(f"  Text:    {scene.get('main_text')}")
            if scene.get("image_search_query"):
                print(f"  Image:   {scene['image_search_query']}")
            print(f"  Narration: {scene.get('narration', '')[:80]}...")

        print("\nValidating script...")
        valid, errs = validate_script(scenes)
        if valid:
            print("PASSED - All checks passed!")
        else:
            print(f"FAILED - {len(errs)} issue(s):")
            for e in errs:
                print(f"  - {e}")
    else:
        print("No script.json found. Run the agent team to generate one.")
